const express = require('express')
const router = express.Router()

const cookie = require('./cookie')
const siteController = require('../controllers/SiteController')

router.get('/', siteController.login)
router.post('/', siteController.check)
router.get('/loginerr', siteController.loginerr)
router.post('/loginerr', siteController.check)
router.get('/paint', siteController.paint)
router.get('/paintlg',cookie.requirelogin, siteController.paintlg)
router.get('/userctrl', cookie.checkadmin , siteController.userctrl)
router.get('/create', siteController.create)
router.post('/create', siteController.store)
router.get('/createrr', siteController.createrr)
router.post('/createrr', siteController.store)
router.get('/admincreate', cookie.checkadmin, siteController.create)
router.post('/admincreate', cookie.checkadmin, siteController.adminstore)
router.get('/admincreaterr', cookie.checkadmin, siteController.createrr)
router.post('/admincreaterr', cookie.checkadmin, siteController.adminstore)
router.get('/userctrl/:id/edit', cookie.checkadmin, siteController.getedit)
router.post('/userctrl/:id/edit', cookie.checkadmin, siteController.postedit)
router.get('/userctrl/:id/delete', cookie.checkadmin, siteController.getdelete)
router.get('/getchangepw',cookie.requirelogin ,siteController.change)
router.post('/getchangepw', siteController.changepw)
router.get('/logout', siteController.logout)

module.exports = router